### ISSUE TITLE
Custom Background image of favorites changes

### ISSUE THREAD

**Issue by mkotzjan** [bartolomesoriano/skin.amber#10]
Amber 3.2.23
Kodi 18.6
LibreElec 9.2.1

I did set up custom background images for the home menu. If I select a menu item the background image in the background is the same as it was in the home menu.
Except for the entry "Favorites". I can see my custom background if I navigate to the "favorites" entry, but when I enter the favorites menu I see the background image of the last menu item I visited.

Steps to reproduce:

1. In the home menu navigate to "Addons"
2. Enter "Addons" menu.
3. Return to the home menu, navigate to "favorites"
4. Enter "favorites".

The background of the "favorites" menu shows the image of the "addons" menu entry. This happens after entering any of the other menus, "favorites" always shows their image.

**Comment by bartolomesoriano** [comment]
@mkotzjan , thanks for pointing this out, I had not noticed.  You are correct, the favourites dialog behaves differently than other menu items.  I have fixed this issue in version 3.2.59 (Leia) and 3.3.59 (Master, for Matrix).  To have the fix occur, you will need to, after updating to 3.2.59, delete the Favourites menu item and then restore it.  You should then see that the action for the menu item is "start_favourites" instead of "ActivateWindow(favourites)".  Alternatively, you can edit the action of the menu item to be "start_favourites" and that should also fix the issue.

The new version is not in the Kodi repo.  It is here in GitHub and in the Amber repos.
