### ISSUE TITLE
have lost shelves overnight 

### ISSUE THREAD

**Issue by gitslit** [bartolomesoriano/skin.amber#8]
overnight i seem to have lost both the Movies and TVshow shelves which display the recently added videos and shows, in progress, unwatched, etc etc 

Ive reset to default , uninstalled the skin , re-installed it but its made no differnece.

Installed a fresh new version of Kodi 18.4 on a new windows 10 pc , added 1 single movie, installed amber skin , Same thing , no shelves :(

**Comment by bartolomesoriano** [comment]
If you upgraded the skin from an old version (before 3.2), you need to configure the shelves yourself, as the skin does not provide any pre-configured shelves anymore ( it has not done so for several months now).  Please go to Settings, Amber Settings, Home Layout, Customize Menu and Shelves and configure your shelves to your liking.

**Comment by gitslit** [comment]
thanks , i've had this working without issue for several moths too , its only just from last night the shelves dissapeared!
to double check this I re-installed kodi 18.3 and installed amber version 3.2.1 and the shelves re-appear as normal 
did this again now with kodi 18.4 and amber 3.2.1 the shelves work just fine too 
If I install amber 3.2.23 then the shelves disspaear on both versions
So I'm guessing you meant to say (before3.2.2)

May I ask what is the benifit to move to the newer "self create" shelf system ? ( other than personal customization )

**Comment by bartolomesoriano** [comment]
Thanks for the additional information. Yes, after 3.2.1 I removed the default shelves functionality, since it was causing multiple problems. 

The configuration of menus, submenus and shelves with script.skinshortcuts allows for total customization that is not possible without it, in terms of number of items, order and in the case of shelves, user control of what the shelves are for each menu item.

If you have further questions or issues configuring your shelves, please ask in the Amber thread in the Kodi forums; I will do my best to answer them.
Thanks.
